language: java
sudo: false
install: true

addons:
  sonarcloud:
    organization: "januson-github"
    token:
      secure: $SONAR_TOKEN

jdk:
  - openjdk11

script:
  - ./gradlew sonarqube

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'

before_install:
  - chmod +x gradlew
  - ./gradlew clean
