version: 2

jobs:
  build:
    working_directory: ~/ulink
    docker:
      - image: circleci/openjdk:11-jdk-browsers
    steps:
      - checkout
      - run:
         name: Chmod permissions
         command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew clean build

  test:
    docker:
      - image: circleci/openjdk:11-jdk-browsers
    steps:
      - checkout
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Run Tests
          command: ./gradlew test sonarQube

workflows:
  version: 2
  pipeline:
    jobs:
      - build
      - test